server {
    listen       80;
    server_name  app.makeitoday.com;
    root   /usr/share/nginx/html;
    index  index.html;

    # Serve all paths to index.html for client-side routing:
    location / {
        try_files $uri $uri/ /index.html;
    }
}